//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityClient.SecurityService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecurityService.ISecurityService")]
    public interface ISecurityService {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://tempuri.org/ISecurityService/None", ReplyAction="http://tempuri.org/ISecurityService/NoneResponse")]
        string None(string message);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://tempuri.org/ISecurityService/None", ReplyAction="http://tempuri.org/ISecurityService/NoneResponse")]
        System.Threading.Tasks.Task<string> NoneAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://tempuri.org/ISecurityService/Sign", ReplyAction="http://tempuri.org/ISecurityService/SignResponse")]
        string Sign(string message);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://tempuri.org/ISecurityService/Sign", ReplyAction="http://tempuri.org/ISecurityService/SignResponse")]
        System.Threading.Tasks.Task<string> SignAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/ISecurityService/SignAndEncrypt", ReplyAction="http://tempuri.org/ISecurityService/SignAndEncryptResponse")]
        string SignAndEncrypt(string message);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/ISecurityService/SignAndEncrypt", ReplyAction="http://tempuri.org/ISecurityService/SignAndEncryptResponse")]
        System.Threading.Tasks.Task<string> SignAndEncryptAsync(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecurityServiceChannel : SecurityClient.SecurityService.ISecurityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecurityServiceClient : System.ServiceModel.ClientBase<SecurityClient.SecurityService.ISecurityService>, SecurityClient.SecurityService.ISecurityService {
        
        public SecurityServiceClient() {
        }
        
        public SecurityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecurityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string None(string message) {
            return base.Channel.None(message);
        }
        
        public System.Threading.Tasks.Task<string> NoneAsync(string message) {
            return base.Channel.NoneAsync(message);
        }
        
        public string Sign(string message) {
            return base.Channel.Sign(message);
        }
        
        public System.Threading.Tasks.Task<string> SignAsync(string message) {
            return base.Channel.SignAsync(message);
        }
        
        public string SignAndEncrypt(string message) {
            return base.Channel.SignAndEncrypt(message);
        }
        
        public System.Threading.Tasks.Task<string> SignAndEncryptAsync(string message) {
            return base.Channel.SignAndEncryptAsync(message);
        }
    }
}
