//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplesClient.SimplesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SimplesService.ISimplesService")]
    public interface ISimplesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplesService/GetEvenNumber", ReplyAction="http://tempuri.org/ISimplesService/GetEvenNumberResponse")]
        int[] GetEvenNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplesService/GetEvenNumber", ReplyAction="http://tempuri.org/ISimplesService/GetEvenNumberResponse")]
        System.Threading.Tasks.Task<int[]> GetEvenNumberAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplesService/GetOddNumber", ReplyAction="http://tempuri.org/ISimplesService/GetOddNumberResponse")]
        int[] GetOddNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplesService/GetOddNumber", ReplyAction="http://tempuri.org/ISimplesService/GetOddNumberResponse")]
        System.Threading.Tasks.Task<int[]> GetOddNumberAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimplesServiceChannel : SimplesClient.SimplesService.ISimplesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimplesServiceClient : System.ServiceModel.ClientBase<SimplesClient.SimplesService.ISimplesService>, SimplesClient.SimplesService.ISimplesService {
        
        public SimplesServiceClient() {
        }
        
        public SimplesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimplesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int[] GetEvenNumber() {
            return base.Channel.GetEvenNumber();
        }
        
        public System.Threading.Tasks.Task<int[]> GetEvenNumberAsync() {
            return base.Channel.GetEvenNumberAsync();
        }
        
        public int[] GetOddNumber() {
            return base.Channel.GetOddNumber();
        }
        
        public System.Threading.Tasks.Task<int[]> GetOddNumberAsync() {
            return base.Channel.GetOddNumberAsync();
        }
    }
}
